@extends('layout.app')

@section('title', ($vehicule->V_IMMATRICULATION ?: $vehicule->V_INDICATIF) . ' — ' . config('app.name'))

@section('content')

<x-ob-breadcrumb :items="[
        ['label' => 'Véhicules', 'url' => route('vehicle.index')],
        ['label' => $vehicule->V_IMMATRICULATION ?: $vehicule->V_INDICATIF],
    ]" />

@php
    $tvIconMap = [
        'ASSU' => 'fas fa-ambulance',
        'VSAV' => 'fas fa-ambulance',
        'VPS' => 'fas fa-ambulance',
        'MPS' => 'fas fa-ambulance',
        'CTU' => 'fas fa-truck',
        'VTU' => 'fas fa-truck',
        'VPI' => 'fas fa-truck',
        'ERS' => 'fas fa-ship',
        'GER' => 'fas fa-bolt',
        'MOTO' => 'fas fa-motorcycle',
        'QUAD' => 'fas fa-motorcycle',
        'PCM' => 'fas fa-satellite-dish',
        'REM' => 'fas fa-trailer',
        'VCYN' => 'fas fa-dog',
        'VELO' => 'fas fa-bicycle',
        'VL' => 'fas fa-car',
        'VLC' => 'fas fa-car',
        'SSV' => 'fas fa-car',
        'VLHR' => 'fas fa-truck-monster',
        'VSR' => 'fas fa-truck-pickup',
        'VTD' => 'fas fa-hard-hat',
        'VTH' => 'fas fa-bed',
        'VTI' => 'fas fa-boxes',
        'VTP' => 'fas fa-bus',
    ];
    $tvIcon = $tvIconMap[$vehicule->TV_CODE ?? ''] ?? 'fas fa-car-side';

    // Expiry-date card helper — returns style props based on urgency
    $today = now()->toDateString();
    $soon = now()->addDays(30)->toDateString();
    $expCard = function ($date, string $label, string $icon) use ($today, $soon) {
        if (!$date) {
            return [
                'label' => $label,
                'icon' => $icon,
                'text' => '—',
                'color' => '#94a3b8',
                'bg' => '#f8fafc',
                'sub' => ''
            ];
        }
        $ds = $date->toDateString();
        $diff = now()->diffInDays($date, false);
        $sub = $diff < 0
            ? 'Expiré il y a ' . abs((int) $diff) . ' j.'
            : 'Dans ' . (int) $diff . ' j.';
        if ($ds < $today) {
            return [
                'label' => $label,
                'icon' => $icon,
                'text' => $date->format('d/m/Y'),
                'color' => '#dc2626',
                'bg' => '#fff1f2',
                'sub' => $sub
            ];
        }
        if ($ds <= $soon) {
            return [
                'label' => $label,
                'icon' => $icon,
                'text' => $date->format('d/m/Y'),
                'color' => '#d97706',
                'bg' => '#fffbeb',
                'sub' => $sub
            ];
        }
        return [
            'label' => $label,
            'icon' => $icon,
            'text' => $date->format('d/m/Y'),
            'color' => '#16a34a',
            'bg' => '#f0fdf4',
            'sub' => $sub
        ];
    };

    $expCards = [
        $expCard($vehicule->V_ASS_DATE, 'Assurance', 'fas fa-shield-alt'),
        $expCard($vehicule->V_CT_DATE, 'Contrôle tech.', 'fas fa-clipboard-check'),
        $expCard($vehicule->V_REV_DATE, 'Révision', 'fas fa-wrench'),
        $expCard($vehicule->V_TITRE_DATE, "Titre d'accès", 'fas fa-id-card'),
    ];

    // Status
    if ($position) {
        [$statusLabel, $statusClass] = match (true) {
            $position->VP_OPERATIONNEL >= 3 => ['Opérationnel', 'ob-badge-actif'],
            $position->VP_OPERATIONNEL >= 1 => ['Limité', 'ob-badge-ben'],
            default => ['Indisponible', 'ob-badge-bloqued'],
        };
    }
@endphp

<div class="mx-3 mt-3">

    <div class="d-flex gap-3 align-items-start">

        {{-- Left sidebar nav — links are generated by ob-vehicle-show.js from the
             [data-veh-section] blocks (their data-nav-* attributes), so the menu
             always matches the sections actually rendered and their order. --}}
        <div class="ob-pers-sidenav-wrap noprint">
            <div class="ob-widget-card">
                <div class="ob-widget-card-body p-0">
                    <nav id="vehSideNav"></nav>
                </div>
            </div>
        </div>

        {{-- Sections column --}}
        <div style="flex:1; min-width:0;">

    {{-- ── Main info card ─────────────────────────────────────────────────────── --}}
    <div id="section-info" data-veh-section data-nav-icon="fas fa-info-circle" data-nav-label="Informations" class="ob-widget-card mb-3">
        <div class="ob-widget-card-header">
            <div class="ob-widget-card-title">
                <i class="{{ $tvIcon }}" title="{{ $vehicleType->TV_LIBELLE ?? $vehicule->TV_CODE }}"></i>
                <span>{{ $vehicule->V_IMMATRICULATION ?: '—' }}</span>
                @if($vehicule->V_INDICATIF)
                    <span class="text-muted fw-normal">— {{ $vehicule->V_INDICATIF }}</span>
                @endif
            </div>
            <div class="d-flex gap-2">
                @if(auth()->user()->hasPermission(17))
                    <a href="{{ route('vehicle.edit', $vehicule->V_ID) }}" class="btn btn-sm btn-outline-secondary">
                        <i class="fas fa-edit me-1"></i> Modifier
                    </a>
                @endif
                <a href="{{ route('vehicle.index') }}" class="btn btn-sm btn-outline-secondary">
                    <i class="fas fa-arrow-left me-1"></i> Retour
                </a>
            </div>
        </div>

        <div class="ob-widget-card-body">
            <div class="row g-4">

                {{-- ── Identity column ─────────────────────────────────────── --}}
                <div class="col-md-5">
                    <dl class="mb-0"
                        style="display:grid; grid-template-columns:auto 1fr; gap:6px 16px; font-size:var(--font-size-sm); align-items:baseline;">

                        <dt class="text-muted fw-normal" style="white-space:nowrap;">Type</dt>
                        <dd class="mb-0">
                            <i class="{{ $tvIcon }} me-1"
                                style="color:var(--text-muted-soft); width:14px; text-align:center;"></i>
                            {{ $vehicleType->TV_LIBELLE ?? ($vehicule->TV_CODE ?: '—') }}
                        </dd>

                        @if($vehicule->V_MODELE || $vehicule->V_ANNEE)
                            <dt class="text-muted fw-normal">Modèle</dt>
                            <dd class="mb-0">
                                {{ trim(($vehicule->V_MODELE ?? '') . ($vehicule->V_ANNEE ? ' (' . $vehicule->V_ANNEE . ')' : '')) ?: '—' }}
                            </dd>
                        @endif

                        <dt class="text-muted fw-normal">Indicatif</dt>
                        <dd class="mb-0 fw-semibold">{{ $vehicule->V_INDICATIF ?: '—' }}</dd>

                        @feature('multi_site')
                        <dt class="text-muted fw-normal">Section</dt>
                        <dd class="mb-0">{{ $vehicule->section?->S_DESCRIPTION ?? '—' }}</dd>
                        @endfeature

                        <dt class="text-muted fw-normal">Statut</dt>
                        <dd class="mb-0">
                            @if($position)
                                <span class="ob-badge {{ $statusClass }}">{{ $position->VP_LIBELLE }}</span>
                            @else
                                <span class="text-muted">—</span>
                            @endif
                        </dd>

                        @if($vehicule->V_KM || $vehicule->V_KM_REVISION)
                            <dt class="text-muted fw-normal">Kilométrage</dt>
                            <dd class="mb-0">
                                @if($vehicule->V_KM)
                                    <span>{{ number_format($vehicule->V_KM, 0, ',', "\u{202f}") }} km</span>
                                @else —
                                @endif
                                @if($vehicule->V_KM_REVISION)
                                    <span class="text-muted ms-2" style="font-size:var(--font-size-xs);">
                                        révision à {{ number_format($vehicule->V_KM_REVISION, 0, ',', "\u{202f}") }} km
                                    </span>
                                @endif
                            </dd>
                        @endif

                        @if($vehicule->V_INVENTAIRE)
                            <dt class="text-muted fw-normal">N° inventaire</dt>
                            <dd class="mb-0">{{ $vehicule->V_INVENTAIRE }}</dd>
                        @endif

                    </dl>

                    {{-- Equipment flags --}}
                    @php $hasFlags = $vehicule->V_FLAG1 || $vehicule->V_FLAG2 || $vehicule->V_FLAG3 || $vehicule->V_FLAG4 || $vehicule->V_EXTERNE; @endphp
                    @if($hasFlags)
                        <div class="d-flex flex-wrap gap-1 mt-3">
                            @if($vehicule->V_FLAG1)
                                <span class="ob-badge ob-badge-int"><i class="fas fa-snowflake me-1"></i>Neige</span>
                            @endif
                            @if($vehicule->V_FLAG2)
                                <span class="ob-badge" style="background:var(--badge-info-bg);color:var(--badge-info-color);"><i
                                        class="fas fa-wind me-1"></i>Climatisation</span>
                            @endif
                            @if($vehicule->V_FLAG3)
                                <span class="ob-badge ob-badge-ben"><i class="fas fa-bullhorn me-1"></i>Public Address</span>
                            @endif
                            @if($vehicule->V_FLAG4)
                                <span class="ob-badge ob-badge-archive"><i class="fas fa-link me-1"></i>Attelage</span>
                            @endif
                            @if($vehicule->V_EXTERNE)
                                <span class="ob-badge ob-badge-ext"><i class="fas fa-external-link-alt me-1"></i>Externe</span>
                            @endif
                        </div>
                    @endif

                    @if($vehicule->V_COMMENT)
                        <p class="mt-3 mb-0 text-muted" style="font-size:var(--font-size-sm); white-space:pre-line;">
                            {{ $vehicule->V_COMMENT }}</p>
                    @endif
                </div>

                {{-- ── Expiry dates column ──────────────────────────────── --}}
                <div class="col-md-7">
                    <div class="row g-2">
                        @foreach($expCards as $card)
                            <div class="col-6">
                                <div style="border-left: 3px solid {{ $card['color'] }};
                                            background: {{ $card['bg'] }};
                                            border-radius: 0 var(--radius-sm) var(--radius-sm) 0;
                                            padding: 10px 14px;">
                                    <div
                                        style="font-size:var(--font-size-xs); color:{{ $card['color'] }}; font-weight:600; margin-bottom:3px;">
                                        <i class="{{ $card['icon'] }} me-1"></i>{{ $card['label'] }}
                                    </div>
                                    <div
                                        style="font-size:1rem; font-weight:700; color:{{ $card['text'] === '—' ? '#94a3b8' : $card['color'] }}; letter-spacing:.01em;">
                                        {{ $card['text'] }}
                                    </div>
                                    @if($card['sub'])
                                        <div
                                            style="font-size:var(--font-size-xs); color:{{ $card['color'] }}; margin-top:2px; opacity:.8;">
                                            {{ $card['sub'] }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>

            </div>{{-- /row --}}
        </div>
    </div>

    {{-- ── Event history ───────────────────────────────────────────────────── --}}
    <div id="section-activites" data-veh-section data-nav-icon="fas fa-history" data-nav-label="Activités" data-nav-badge="{{ ($vehicleStats->total_events ?? 0) ?: '' }}" class="ob-widget-card mb-3">
        <div class="ob-widget-card-header">
            <div class="ob-widget-card-title">
                <i class="fas fa-history"></i> Activités
                @if($vehicleStats && $vehicleStats->total_events)
                    <span class="ob-badge ob-badge-archive ms-1">{{ $vehicleStats->total_events }}</span>
                @endif
            </div>
            {{-- Year filter --}}
            @if($eventYears->isNotEmpty())
                <form method="GET" class="d-flex align-items-center gap-1">
                    <select name="year" class="form-select form-select-sm" style="width:auto;"
                            onchange="this.form.submit()">
                        @foreach($eventYears as $y)
                            <option value="{{ $y }}" @selected($y == $year)>{{ $y }}</option>
                        @endforeach
                    </select>
                </form>
            @endif
        </div>

        {{-- Stats row --}}
        @if($vehicleStats && ($vehicleStats->total_events || $vehicleStats->total_km))
            <div class="ob-widget-card-body border-bottom py-2 px-3 d-flex gap-4" style="font-size:var(--font-size-sm);">
                <span>
                    <span class="text-muted">Total engagements :</span>
                    <strong>{{ number_format((int)$vehicleStats->total_events, 0, ',', "\u{202f}") }}</strong>
                </span>
                @if($vehicleStats->total_km)
                    <span>
                        <span class="text-muted">Km cumulés :</span>
                        <strong>{{ number_format((int)$vehicleStats->total_km, 0, ',', "\u{202f}") }} km</strong>
                    </span>
                @endif
            </div>
        @endif

        <div class="ob-widget-card-body p-0">
            @if($eventHistory->isEmpty())
                <p class="ob-widget-empty p-3">Aucune activité en {{ $year }}.</p>
            @else
                <table class="table table-sm table-hover mb-0">
                    <thead style="background:var(--table-header-bg);color:var(--table-header-text)">
                        <tr>
                            <th>Activité</th>
                            <th>Fonction</th>
                            <th>Date</th>
                            <th class="text-end">Km</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($eventHistory as $ev)
                            <tr>
                                <td style="font-size:var(--font-size-sm)">
                                    <a href="{{ route('event.show', $ev->E_CODE) }}" class="text-decoration-none">
                                        {{ $ev->E_LIBELLE ?? $ev->E_CODE }}
                                    </a>
                                </td>
                                <td style="font-size:var(--font-size-xs);color:var(--text-muted-soft)">
                                    {{ $ev->TFV_NAME ?? '—' }}
                                </td>
                                <td style="font-size:var(--font-size-xs);color:var(--text-muted-soft)">
                                    {{ $ev->EH_DATE_DEBUT ? \Carbon\Carbon::parse($ev->EH_DATE_DEBUT)->format('d/m/Y') : '—' }}
                                </td>
                                <td class="text-end" style="font-size:var(--font-size-xs);color:var(--text-muted-soft)">
                                    {{ $ev->EV_KM ? number_format($ev->EV_KM, 0, ',', "\u{202f}") . ' km' : '—' }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                @if($eventHistory->hasPages())
                    <div class="p-2 border-top">{{ $eventHistory->links() }}</div>
                @endif
            @endif
        </div>
    </div>

    {{-- ── Matériel embarqué ────────────────────────────────────────────────── --}}
    <div id="section-materiel" data-veh-section data-nav-icon="fas fa-boxes" data-nav-label="Matériel" data-nav-badge="{{ $materiels->count() ?: '' }}" class="ob-widget-card mb-3">
        <div class="ob-widget-card-header">
            <div class="ob-widget-card-title">
                <i class="fas fa-boxes"></i> Matériel embarqué
                @if($materiels->isNotEmpty())
                    <span class="ob-badge ob-badge-archive ms-1">{{ $materiels->count() }}</span>
                @endif
            </div>
            @if(auth()->user()->hasPermission(17) && $availableEquipment->isNotEmpty())
                <form method="POST" action="{{ route('vehicle.equipment.attach', $vehicule->V_ID) }}"
                      class="d-flex align-items-center gap-1">
                    @csrf
                    <select name="MA_ID" class="form-select form-select-sm" style="max-width:280px;" required>
                        <option value="">— Embarquer du matériel —</option>
                        @php $prevType = null; @endphp
                        @foreach($availableEquipment as $eq)
                            @if($eq->TM_DESCRIPTION !== $prevType)
                                @if($prevType !== null)</optgroup>@endif
                                <optgroup label="{{ $eq->TM_DESCRIPTION ?? $eq->TM_CODE ?? 'Autre' }}">
                                @php $prevType = $eq->TM_DESCRIPTION; @endphp
                            @endif
                            <option value="{{ $eq->MA_ID }}">
                                {{ $eq->MA_MODELE ?: '—' }}
                                @if($eq->MA_NUMERO_SERIE) — {{ $eq->MA_NUMERO_SERIE }} @endif
                            </option>
                        @endforeach
                        @if($prevType !== null)</optgroup>@endif
                    </select>
                    <button type="submit" class="btn btn-sm btn-outline-primary flex-shrink-0">
                        <i class="fas fa-plus"></i>
                    </button>
                </form>
            @endif
        </div>
        <div class="ob-widget-card-body p-0">
            @if($materiels->isEmpty())
                <p class="ob-widget-empty p-3">Aucun matériel assigné à ce véhicule.</p>
            @else
                <table class="table table-sm table-hover mb-0">
                    <thead style="background:var(--table-header-bg);color:var(--table-header-text)">
                        <tr>
                            <th>Type</th>
                            <th>Modèle</th>
                            <th>N° série</th>
                            <th>Inventaire</th>
                            <th class="text-end">Qté</th>
                            @if(auth()->user()->hasPermission(17))<th></th>@endif
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($materiels as $mat)
                            <tr>
                                <td style="font-size:var(--font-size-sm)">{{ $mat->TM_DESCRIPTION ?? $mat->TM_CODE ?? '—' }}</td>
                                <td style="font-size:var(--font-size-sm)">{{ $mat->MA_MODELE ?: '—' }}</td>
                                <td style="font-size:var(--font-size-xs);color:var(--text-muted-soft)">
                                    {{ $mat->MA_NUMERO_SERIE ?: '—' }}</td>
                                <td style="font-size:var(--font-size-xs);color:var(--text-muted-soft)">
                                    {{ $mat->MA_INVENTAIRE ?: '—' }}</td>
                                <td class="text-end" style="font-size:var(--font-size-sm)">{{ $mat->MA_NB ?? 1 }}</td>
                                @if(auth()->user()->hasPermission(17))
                                    <td class="text-end">
                                        <form method="POST"
                                              action="{{ route('vehicle.equipment.detach', [$vehicule->V_ID, $mat->MA_ID]) }}"
                                              onsubmit="return confirm('Débarquer ce matériel ?')">
                                            @csrf @method('DELETE')
                                            <button type="submit" class="btn btn-xs btn-outline-danger"
                                                    style="font-size:var(--font-size-xs);padding:1px 6px;"
                                                    title="Débarquer">
                                                <i class="fas fa-times"></i>
                                            </button>
                                        </form>
                                    </td>
                                @endif
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

    {{-- ── Documents ────────────────────────────────────────────────────────── --}}
    <div id="section-documents" data-veh-section data-nav-icon="fas fa-file-alt" data-nav-label="Documents" data-nav-badge="{{ $documents->count() ?: '' }}" class="ob-widget-card mb-3">
        <div class="ob-widget-card-header">
            <div class="ob-widget-card-title">
                <i class="fas fa-file-alt"></i> Documents
                @if($documents->isNotEmpty())
                    <span class="ob-badge ob-badge-archive ms-1">{{ $documents->count() }}</span>
                @endif
            </div>
        </div>
        <div class="ob-widget-card-body p-0">
            @if($documents->isEmpty())
                <p class="ob-widget-empty p-3">Aucun document associé à ce véhicule.</p>
            @else
                <table class="table table-sm table-hover mb-0">
                    <thead style="background:var(--table-header-bg);color:var(--table-header-text)">
                        <tr>
                            <th>Nom</th>
                            <th>Catégorie</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($documents as $doc)
                            <tr>
                                <td style="font-size:var(--font-size-sm)">
                                    <i class="fas fa-file-alt text-muted me-1"></i>{{ $doc->D_NAME }}
                                </td>
                                <td style="font-size:var(--font-size-xs);color:var(--text-muted-soft)">
                                    {{ $doc->TD_LIBELLE ?? '—' }}</td>
                                <td style="font-size:var(--font-size-xs);color:var(--text-muted-soft)">
                                    {{ $doc->D_CREATED_DATE ? \Carbon\Carbon::parse($doc->D_CREATED_DATE)->format('d/m/Y') : '—' }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

        </div>  {{-- close sections column --}}
    </div>  {{-- close content (flex) --}}

</div>

@push('scripts')
@vite('resources/js/ob-vehicle-show.js')
@endpush

@endsection