<?php

declare(strict_types=1);

use App\Http\Controllers\Legacy\LegacyBridgeController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth')->prefix('legacy')->group(function () {
    Route::match(['GET', 'POST'], 'about.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.about');
    Route::match(['GET', 'POST'], 'addons.php', [LegacyBridgeController::class, 'show'])->middleware('permission:78')->name('legacy_bridge.addons');
    Route::match(['GET', 'POST'], 'addons_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:78')->name('legacy_bridge.addons_save');
    Route::match(['GET', 'POST'], 'alerte_create.php', [LegacyBridgeController::class, 'show'])->middleware('permission:43')->name('legacy_bridge.alerte_create');
    Route::match(['GET', 'POST'], 'alerte_send.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.alerte_send');
    Route::match(['GET', 'POST'], 'astreinte_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:26')->name('legacy_bridge.astreinte_edit');
    Route::match(['GET', 'POST'], 'astreinte_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:26')->name('legacy_bridge.astreinte_save');
    Route::match(['GET', 'POST'], 'astreintes.php', fn () => redirect()->route('garde.astreintes'))->name('legacy_bridge.astreintes');
    Route::match(['GET', 'POST'], 'astreintes_updates.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.astreintes_updates');
    Route::match(['GET', 'POST'], 'audit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:20')->name('legacy_bridge.audit');
    Route::match(['GET', 'POST'], 'auto_garde.php', [LegacyBridgeController::class, 'show'])->middleware('permission:6')->name('legacy_bridge.auto_garde');
    Route::match(['GET', 'POST'], 'automaticPiquet.php', [LegacyBridgeController::class, 'show'])->middleware('permission:6')->name('legacy_bridge.automaticPiquet');
    Route::match(['GET', 'POST'], 'backup.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.backup');
    Route::match(['GET', 'POST'], 'bilan_participation.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.bilan_participation');
    Route::match(['GET', 'POST'], 'bilans.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.bilans');
    Route::match(['GET', 'POST'], 'browscap.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.browscap');
    Route::match(['GET', 'POST'], 'buildsql.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.buildsql');
    Route::match(['GET', 'POST'], 'buildzipcode.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.buildzipcode');
    Route::match(['GET', 'POST'], 'calendar.php', fn () => redirect()->route('planning.index'))->name('legacy_bridge.calendar');
    Route::match(['GET', 'POST'], 'cav_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.cav_edit');
    Route::match(['GET', 'POST'], 'change_password.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.change_password');
    Route::match(['GET', 'POST'], 'charte.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.charte');
    Route::match(['GET', 'POST'], 'chat.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.chat');
    Route::match(['GET', 'POST'], 'chat_message.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.chat_message');
    Route::match(['GET', 'POST'], 'choice_section_order.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.choice_section_order');
    Route::match(['GET', 'POST'], 'company.php', fn () => redirect()->route('company.index'))->name('legacy_bridge.company');
    Route::match(['GET', 'POST'], 'company_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:29')->name('legacy_bridge.company_xls');
    Route::match(['GET', 'POST'], 'config_doc.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.config_doc');
    Route::match(['GET', 'POST'], 'config_prelevements.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.config_prelevements');
    Route::match(['GET', 'POST'], 'configuration.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.configuration');
    Route::match(['GET', 'POST'], 'configuration_db.php', fn () => redirect()->route('dashboard'))->name('legacy_bridge.configuration_db');
    Route::match(['GET', 'POST'], 'configuration_icone_grade.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.configuration_icone_grade');
    Route::match(['GET', 'POST'], 'configuration_theme.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.configuration_theme');
    Route::match(['GET', 'POST'], 'connected_users.php', [LegacyBridgeController::class, 'show'])->middleware('permission:20')->name('legacy_bridge.connected_users');
    Route::match(['GET', 'POST'], 'consommable.php', fn () => redirect()->route('consommable.index'))->name('legacy_bridge.consommable');
    Route::match(['GET', 'POST'], 'consommable_load.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.consommable_load');
    Route::match(['GET', 'POST'], 'consommable_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.consommable_xls');
    Route::match(['GET', 'POST'], 'cotisation_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.cotisation_edit');
    Route::match(['GET', 'POST'], 'cotisations.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.cotisations');
    Route::match(['GET', 'POST'], 'cotisations_extract.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.cotisations_extract');
    Route::match(['GET', 'POST'], 'cotisations_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.cotisations_xls');
    Route::match(['GET', 'POST'], 'database_maintenance.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.database_maintenance');
    Route::match(['GET', 'POST'], 'debug_data.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.debug_data');
    Route::match(['GET', 'POST'], 'decrypt.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.decrypt');
    Route::match(['GET', 'POST'], 'del_categorie_grade.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_categorie_grade');
    Route::match(['GET', 'POST'], 'del_company.php', [LegacyBridgeController::class, 'show'])->middleware('permission:19')->name('legacy_bridge.del_company');
    Route::match(['GET', 'POST'], 'del_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:71')->name('legacy_bridge.del_consommable');
    Route::match(['GET', 'POST'], 'del_edit_categorie.php', [LegacyBridgeController::class, 'show'])->middleware('permission:19')->name('legacy_bridge.del_edit_categorie');
    Route::match(['GET', 'POST'], 'del_edit_categorie_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:19')->name('legacy_bridge.del_edit_categorie_consommable');
    Route::match(['GET', 'POST'], 'del_element_facturable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:29')->name('legacy_bridge.del_element_facturable');
    Route::match(['GET', 'POST'], 'del_equipe.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_equipe');
    Route::match(['GET', 'POST'], 'del_grade.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_grade');
    Route::match(['GET', 'POST'], 'del_groupe.php', [LegacyBridgeController::class, 'show'])->middleware('permission:9')->name('legacy_bridge.del_groupe');
    Route::match(['GET', 'POST'], 'del_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:70')->name('legacy_bridge.del_materiel');
    Route::match(['GET', 'POST'], 'del_personnel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:3')->name('legacy_bridge.del_personnel');
    Route::match(['GET', 'POST'], 'del_personnel_formation.php', [LegacyBridgeController::class, 'show'])->middleware('permission:4')->name('legacy_bridge.del_personnel_formation');
    Route::match(['GET', 'POST'], 'del_poste.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_poste');
    Route::match(['GET', 'POST'], 'del_section.php', [LegacyBridgeController::class, 'show'])->middleware('permission:19')->name('legacy_bridge.del_section');
    Route::match(['GET', 'POST'], 'del_type_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_type_consommable');
    Route::match(['GET', 'POST'], 'del_type_evenement.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_type_evenement');
    Route::match(['GET', 'POST'], 'del_type_garde.php', [LegacyBridgeController::class, 'show'])->middleware('permission:5')->name('legacy_bridge.del_type_garde');
    Route::match(['GET', 'POST'], 'del_type_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_type_materiel');
    Route::match(['GET', 'POST'], 'del_type_vehicule.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.del_type_vehicule');
    Route::match(['GET', 'POST'], 'del_vehicule.php', [LegacyBridgeController::class, 'show'])->middleware('permission:19')->name('legacy_bridge.del_vehicule');
    Route::match(['GET', 'POST'], 'delete_event_file.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.delete_event_file');
    Route::match(['GET', 'POST'], 'delete_file.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.delete_file');
    Route::match(['GET', 'POST'], 'delete_message.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.delete_message');
    Route::match(['GET', 'POST'], 'delete_statistique.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.delete_statistique');
    Route::match(['GET', 'POST'], 'deletePompier.php', [LegacyBridgeController::class, 'show'])->middleware('permission:6')->name('legacy_bridge.deletePompier');
    Route::match(['GET', 'POST'], 'demande_renfort.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.demande_renfort');
    Route::match(['GET', 'POST'], 'departement.php', [LegacyBridgeController::class, 'show'])->middleware('permission:52')->name('legacy_bridge.departement');
    Route::match(['GET', 'POST'], 'destinataires.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.destinataires');
    Route::match(['GET', 'POST'], 'diplome_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:54')->name('legacy_bridge.diplome_edit');
    Route::match(['GET', 'POST'], 'dispo.php', [LegacyBridgeController::class, 'show'])->middleware('permission:38')->name('legacy_bridge.dispo');
    Route::match(['GET', 'POST'], 'document_modal.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.document_modal');
    Route::match(['GET', 'POST'], 'documents.php', fn () => redirect()->route('document.index'))->name('legacy_bridge.documents');
    Route::match(['GET', 'POST'], 'download_addon.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.download_addon');
    Route::match(['GET', 'POST'], 'download_module.php', [LegacyBridgeController::class, 'show'])->middleware('permission:78')->name('legacy_bridge.download_module');
    Route::match(['GET', 'POST'], 'download_package.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.download_package');
    Route::match(['GET', 'POST'], 'dps.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.dps');
    Route::match(['GET', 'POST'], 'dps_calc.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.dps_calc');
    Route::match(['GET', 'POST'], 'dps_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:15')->name('legacy_bridge.dps_save');
    Route::match(['GET', 'POST'], 'edit_categorie.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.edit_categorie');
    Route::match(['GET', 'POST'], 'edit_categorie_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.edit_categorie_consommable');
    Route::match(['GET', 'POST'], 'edit_categorie_grades.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.edit_categorie_grades');
    Route::match(['GET', 'POST'], 'edit_grades.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.edit_grades');
    Route::match(['GET', 'POST'], 'element_facturable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:29')->name('legacy_bridge.element_facturable');
    Route::match(['GET', 'POST'], 'equipe.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.equipe');
    Route::match(['GET', 'POST'], 'error.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.error');
    Route::match(['GET', 'POST'], 'evenement_add_renfort.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_add_renfort');
    Route::match(['GET', 'POST'], 'evenement_choice.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_choice');
    Route::match(['GET', 'POST'], 'evenement_competences.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_competences');
    Route::match(['GET', 'POST'], 'evenement_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.evenement_consommable');
    Route::match(['GET', 'POST'], 'evenement_consommable_add.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_consommable_add');
    Route::match(['GET', 'POST'], 'evenement_detail.php', function (\Illuminate\Http\Request $r) {
        $code = $r->query('evenement');
        return $code
            ? redirect()->route('evenement.show', $code)
            : redirect()->route('evenement.index');
    })->name('legacy_bridge.evenement_detail');
    Route::match(['GET', 'POST'], 'evenement_diplome.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_diplome');
    Route::match(['GET', 'POST'], 'evenement_display.php', fn () => redirect()->route('evenement.index'))->name('legacy_bridge.evenement_display');
    Route::match(['GET', 'POST'], 'evenement_duplicate.php', [LegacyBridgeController::class, 'show'])->middleware('permission:15')->name('legacy_bridge.evenement_duplicate');
    Route::match(['GET', 'POST'], 'evenement_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_edit');
    Route::match(['GET', 'POST'], 'evenement_equipes.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.evenement_equipes');
    Route::match(['GET', 'POST'], 'evenement_facturation.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_facturation');
    Route::match(['GET', 'POST'], 'evenement_facturation_detail.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_facturation_detail');
    Route::match(['GET', 'POST'], 'evenement_facturation_num.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_facturation_num');
    Route::match(['GET', 'POST'], 'evenement_garde.php', [LegacyBridgeController::class, 'show'])->middleware('permission:6')->name('legacy_bridge.evenement_garde');
    Route::match(['GET', 'POST'], 'evenement_horaires.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_horaires');
    Route::match(['GET', 'POST'], 'evenement_ical.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_ical');
    Route::match(['GET', 'POST'], 'evenement_info_participant.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.evenement_info_participant');
    Route::match(['GET', 'POST'], 'evenement_inscription.php', [LegacyBridgeController::class, 'show'])->middleware('permission:39')->name('legacy_bridge.evenement_inscription');
    Route::match(['GET', 'POST'], 'evenement_list_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_list_xls');
    Route::match(['GET', 'POST'], 'evenement_materiel_add.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_materiel_add');
    Route::match(['GET', 'POST'], 'evenement_modal.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_modal');
    Route::match(['GET', 'POST'], 'evenement_multi_renforts.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_multi_renforts');
    Route::match(['GET', 'POST'], 'evenement_notify.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_notify');
    Route::match(['GET', 'POST'], 'evenement_option_choix.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.evenement_option_choix');
    Route::match(['GET', 'POST'], 'evenement_options.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.evenement_options');
    Route::match(['GET', 'POST'], 'evenement_rapport.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_rapport');
    Route::match(['GET', 'POST'], 'evenement_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_save');
    Route::match(['GET', 'POST'], 'evenement_tarif.php', [LegacyBridgeController::class, 'show'])->middleware('permission:15')->name('legacy_bridge.evenement_tarif');
    Route::match(['GET', 'POST'], 'evenement_tarif_formation.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.evenement_tarif_formation');
    Route::match(['GET', 'POST'], 'evenement_trombinoscope.php', [LegacyBridgeController::class, 'show'])->middleware('permission:44')->name('legacy_bridge.evenement_trombinoscope');
    Route::match(['GET', 'POST'], 'evenement_vehicule_add.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.evenement_vehicule_add');
    Route::match(['GET', 'POST'], 'evenement_vehicule_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.evenement_vehicule_xls');
    Route::match(['GET', 'POST'], 'evenement_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.evenement_xls');
    Route::match(['GET', 'POST'], 'evenements.php', fn () => redirect()->route('evenement.index'))->name('legacy_bridge.evenements');
    Route::match(['GET', 'POST'], 'export-html.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.export_html');
    Route::match(['GET', 'POST'], 'export-sql-liste.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.export_sql_liste');
    Route::match(['GET', 'POST'], 'export-sql.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.export_sql');
    Route::match(['GET', 'POST'], 'export-tcd.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.export_tcd');
    Route::match(['GET', 'POST'], 'export-txt.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.export_txt');
    Route::match(['GET', 'POST'], 'export-xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.export_xls');
    Route::match(['GET', 'POST'], 'export.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.export');
    Route::match(['GET', 'POST'], 'export_badges.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.export_badges');
    Route::match(['GET', 'POST'], 'feuille_garde.php', fn () => redirect()->route('garde.index'))->name('legacy_bridge.feuille_garde');
    Route::match(['GET', 'POST'], 'formations_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.formations_xls');
    Route::match(['GET', 'POST'], 'geolocalize_all_persons.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.geolocalize_all_persons');
    Route::match(['GET', 'POST'], 'gmaps_evenement.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.gmaps_evenement');
    Route::match(['GET', 'POST'], 'gmaps_personnel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:76')->name('legacy_bridge.gmaps_personnel');
    Route::match(['GET', 'POST'], 'gps.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.gps');
    Route::match(['GET', 'POST'], 'gps_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.gps_save');
    Route::match(['GET', 'POST'], 'gps_save2.php', [LegacyBridgeController::class, 'show'])->middleware('permission:76')->name('legacy_bridge.gps_save2');
    Route::match(['GET', 'POST'], 'grades_load.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.grades_load');
    Route::match(['GET', 'POST'], 'habilitations.php', [LegacyBridgeController::class, 'show'])->middleware('permission:52')->name('legacy_bridge.habilitations');
    Route::match(['GET', 'POST'], 'habilitations_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:40')->name('legacy_bridge.habilitations_xls');
    Route::match(['GET', 'POST'], 'hierarchie_competence.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.hierarchie_competence');
    Route::match(['GET', 'POST'], 'histo_sms.php', [LegacyBridgeController::class, 'show'])->middleware('permission:23')->name('legacy_bridge.histo_sms');
    Route::match(['GET', 'POST'], 'history.php', [LegacyBridgeController::class, 'show'])->middleware('permission:49')->name('legacy_bridge.history');
    Route::match(['GET', 'POST'], 'homonymes_manage.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.homonymes_manage');
    Route::match(['GET', 'POST'], 'homonymes_modal.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.homonymes_modal');
    Route::match(['GET', 'POST'], 'horaires.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.horaires');
    Route::match(['GET', 'POST'], 'horaires_modal.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.horaires_modal');
    Route::match(['GET', 'POST'], 'import_api.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.import_api');
    Route::match(['GET', 'POST'], 'index.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.index');
    Route::match(['GET', 'POST'], 'index_d.php', fn () => redirect()->route('dashboard'))->name('legacy_bridge.index_d');
    Route::match(['GET', 'POST'], 'indispo.php', [LegacyBridgeController::class, 'show'])->middleware('permission:11')->name('legacy_bridge.indispo');
    Route::match(['GET', 'POST'], 'indispo_choice.php', [LegacyBridgeController::class, 'show'])->middleware('permission:11')->name('legacy_bridge.indispo_choice');
    Route::match(['GET', 'POST'], 'indispo_display.php', [LegacyBridgeController::class, 'show'])->middleware('permission:11')->name('legacy_bridge.indispo_display');
    Route::match(['GET', 'POST'], 'indispo_list_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:56')->name('legacy_bridge.indispo_list_xls');
    Route::match(['GET', 'POST'], 'indispo_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:11')->name('legacy_bridge.indispo_save');
    Route::match(['GET', 'POST'], 'indispo_status.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.indispo_status');
    Route::match(['GET', 'POST'], 'ins_company.php', [LegacyBridgeController::class, 'show'])->middleware('permission:29')->name('legacy_bridge.ins_company');
    Route::match(['GET', 'POST'], 'ins_groupe.php', [LegacyBridgeController::class, 'show'])->middleware('permission:9')->name('legacy_bridge.ins_groupe');
    Route::match(['GET', 'POST'], 'ins_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:70')->name('legacy_bridge.ins_materiel');
    Route::match(['GET', 'POST'], 'ins_personnel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.ins_personnel');
    Route::match(['GET', 'POST'], 'ins_poste.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.ins_poste');
    Route::match(['GET', 'POST'], 'ins_section.php', [LegacyBridgeController::class, 'show'])->middleware('permission:55')->name('legacy_bridge.ins_section');
    Route::match(['GET', 'POST'], 'ins_type_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.ins_type_materiel');
    Route::match(['GET', 'POST'], 'ins_vehicule.php', [LegacyBridgeController::class, 'show'])->middleware('permission:17')->name('legacy_bridge.ins_vehicule');
    Route::match(['GET', 'POST'], 'install_addon.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.install_addon');
    Route::match(['GET', 'POST'], 'intervention_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.intervention_edit');
    Route::match(['GET', 'POST'], 'jvectormap.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.jvectormap');
    Route::match(['GET', 'POST'], 'liste_victimes.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.liste_victimes');
    Route::match(['GET', 'POST'], 'listecontacts.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.listecontacts');
    Route::match(['GET', 'POST'], 'listemails.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.listemails');
    Route::match(['GET', 'POST'], 'livesearch.php', [LegacyBridgeController::class, 'show'])->middleware('permission:40')->name('legacy_bridge.livesearch');
    Route::match(['GET', 'POST'], 'localize.php', [LegacyBridgeController::class, 'show'])->middleware('permission:43')->name('legacy_bridge.localize');
    Route::match(['GET', 'POST'], 'localize_me.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.localize_me');
    Route::match(['GET', 'POST'], 'localize_send.php', [LegacyBridgeController::class, 'show'])->middleware('permission:23')->name('legacy_bridge.localize_send');
    Route::match(['GET', 'POST'], 'lost_password.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.lost_password');
    Route::match(['GET', 'POST'], 'lost_session.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.lost_session');
    Route::match(['GET', 'POST'], 'mail_create.php', [LegacyBridgeController::class, 'show'])->middleware('permission:43')->name('legacy_bridge.mail_create');
    Route::match(['GET', 'POST'], 'mail_create_input.php', [LegacyBridgeController::class, 'show'])->middleware('permission:43')->name('legacy_bridge.mail_create_input');
    Route::match(['GET', 'POST'], 'mail_send.php', [LegacyBridgeController::class, 'show'])->middleware('permission:43')->name('legacy_bridge.mail_send');
    Route::match(['GET', 'POST'], 'mailer.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.mailer');
    Route::match(['GET', 'POST'], 'mailto.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.mailto');
    Route::match(['GET', 'POST'], 'map.php', [LegacyBridgeController::class, 'show'])->middleware('permission:76')->name('legacy_bridge.map');
    Route::match(['GET', 'POST'], 'materiel.php', fn () => redirect()->route('materiel.index'))->name('legacy_bridge.materiel');
    Route::match(['GET', 'POST'], 'materiel_embarquer.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.materiel_embarquer');
    Route::match(['GET', 'POST'], 'materiel_load.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.materiel_load');
    Route::match(['GET', 'POST'], 'materiel_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.materiel_xls');
    Route::match(['GET', 'POST'], 'membres.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.membres');
    Route::match(['GET', 'POST'], 'menu_status_set.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.menu_status_set');
    Route::match(['GET', 'POST'], 'message.php', function (\Illuminate\Http\Request $r) {
        $cat = $r->query('catmessage', 'consigne');
        return redirect()->route('message.index', ['category' => $cat]);
    })->name('legacy_bridge.message');
    Route::match(['GET', 'POST'], 'myagenda.php', fn () => redirect()->route('planning.index'))->name('legacy_bridge.myagenda');
    Route::match(['GET', 'POST'], 'noscript.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.noscript');
    Route::match(['GET', 'POST'], 'note_frais_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:77')->name('legacy_bridge.note_frais_edit');
    Route::match(['GET', 'POST'], 'note_frais_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:77')->name('legacy_bridge.note_frais_save');
    Route::match(['GET', 'POST'], 'observations_modal.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.observations_modal');
    Route::match(['GET', 'POST'], 'organigramme.php', fn () => redirect()->route('organisation.index'))->name('legacy_bridge.organigramme');
    Route::match(['GET', 'POST'], 'parametrage.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.parametrage');
    Route::match(['GET', 'POST'], 'paramfn.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.paramfn');
    Route::match(['GET', 'POST'], 'paramfn_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.paramfn_edit');
    Route::match(['GET', 'POST'], 'paramfn_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.paramfn_save');
    Route::match(['GET', 'POST'], 'paramfnv.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.paramfnv');
    Route::match(['GET', 'POST'], 'paramfnv_edit.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.paramfnv_edit');
    Route::match(['GET', 'POST'], 'paramfnv_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.paramfnv_save');
    Route::match(['GET', 'POST'], 'participations_modal.php', [LegacyBridgeController::class, 'show'])->middleware('permission:56')->name('legacy_bridge.participations_modal');
    Route::match(['GET', 'POST'], 'pdf.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf');
    Route::match(['GET', 'POST'], 'pdf_asa.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_asa');
    Route::match(['GET', 'POST'], 'pdf_attestation_fiscale.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_attestation_fiscale');
    Route::match(['GET', 'POST'], 'pdf_attestation_formation.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_attestation_formation');
    Route::match(['GET', 'POST'], 'pdf_bilans.php', [LegacyBridgeController::class, 'show'])->middleware('permission:27')->name('legacy_bridge.pdf_bilans');
    Route::match(['GET', 'POST'], 'pdf_bulletin.php', [LegacyBridgeController::class, 'show'])->middleware('permission:44')->name('legacy_bridge.pdf_bulletin');
    Route::match(['GET', 'POST'], 'pdf_carte_adherent.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_carte_adherent');
    Route::match(['GET', 'POST'], 'pdf_courrier_nouvel_adherent.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_courrier_nouvel_adherent');
    Route::match(['GET', 'POST'], 'pdf_diplome.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_diplome');
    Route::match(['GET', 'POST'], 'pdf_document.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_document');
    Route::match(['GET', 'POST'], 'pdf_livret.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.pdf_livret');
    Route::match(['GET', 'POST'], 'personnel.php', fn () => redirect()->route('personnel.index'))->name('legacy_bridge.personnel');
    Route::match(['GET', 'POST'], 'personnel_contact.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_contact');
    Route::match(['GET', 'POST'], 'personnel_evenement_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_evenement_xls');
    Route::match(['GET', 'POST'], 'personnel_formation.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_formation');
    Route::match(['GET', 'POST'], 'personnel_load.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_load');
    Route::match(['GET', 'POST'], 'personnel_maitre.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_maitre');
    Route::match(['GET', 'POST'], 'personnel_preferences.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_preferences');
    Route::match(['GET', 'POST'], 'personnel_reunion_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_reunion_xls');
    Route::match(['GET', 'POST'], 'personnel_tenues.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_tenues');
    Route::match(['GET', 'POST'], 'personnel_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.personnel_xls');
    Route::match(['GET', 'POST'], 'planning.php', [LegacyBridgeController::class, 'show'])->middleware('permission:56')->name('legacy_bridge.planning');
    Route::match(['GET', 'POST'], 'planning_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:56')->name('legacy_bridge.planning_xls');
    Route::match(['GET', 'POST'], 'poste.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.poste');
    Route::match(['GET', 'POST'], 'prelevements.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.prelevements');
    Route::match(['GET', 'POST'], 'push_monitor.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.push_monitor');
    Route::match(['GET', 'POST'], 'qrcode.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.qrcode');
    Route::match(['GET', 'POST'], 'qrcode_pic.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.qrcode_pic');
    Route::match(['GET', 'POST'], 'qualifications.php', fn () => redirect()->route('personnel.qualifications'))->name('legacy_bridge.qualifications');
    Route::match(['GET', 'POST'], 'qualifications_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.qualifications_xls');
    Route::match(['GET', 'POST'], 'radier_section.php', [LegacyBridgeController::class, 'show'])->middleware('permission:22')->name('legacy_bridge.radier_section');
    Route::match(['GET', 'POST'], 'rebuild_section_flat.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.rebuild_section_flat');
    Route::match(['GET', 'POST'], 'reminder.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.reminder');
    Route::match(['GET', 'POST'], 'remplacement_edit.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.remplacement_edit');
    Route::match(['GET', 'POST'], 'remplacements.php', [LegacyBridgeController::class, 'show'])->middleware('permission:41')->name('legacy_bridge.remplacements');
    Route::match(['GET', 'POST'], 'repo_events.php', fn () => redirect()->route('statistique.index'))->name('legacy_bridge.repo_events');
    Route::match(['GET', 'POST'], 'report_cotisations.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.report_cotisations');
    Route::match(['GET', 'POST'], 'repos_saisie.php', [LegacyBridgeController::class, 'show'])->middleware('permission:10')->name('legacy_bridge.repos_saisie');
    Route::match(['GET', 'POST'], 'repos_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.repos_save');
    Route::match(['GET', 'POST'], 'restore.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.restore');
    Route::match(['GET', 'POST'], 'rss.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.rss');
    Route::match(['GET', 'POST'], 'save_accueil.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_accueil');
    Route::match(['GET', 'POST'], 'save_company.php', [LegacyBridgeController::class, 'show'])->middleware('permission:29')->name('legacy_bridge.save_company');
    Route::match(['GET', 'POST'], 'save_configuration.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.save_configuration');
    Route::match(['GET', 'POST'], 'save_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_consommable');
    Route::match(['GET', 'POST'], 'save_cotisations.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.save_cotisations');
    Route::match(['GET', 'POST'], 'save_detail_facture.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_detail_facture');
    Route::match(['GET', 'POST'], 'save_dispo.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_dispo');
    Route::match(['GET', 'POST'], 'save_documents.php', [LegacyBridgeController::class, 'show'])->middleware('permission:47')->name('legacy_bridge.save_documents');
    Route::match(['GET', 'POST'], 'save_edit_categorie.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_edit_categorie');
    Route::match(['GET', 'POST'], 'save_edit_categorie_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_edit_categorie_consommable');
    Route::match(['GET', 'POST'], 'save_edit_categorie_grades.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_edit_categorie_grades');
    Route::match(['GET', 'POST'], 'save_element_facturable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:17')->name('legacy_bridge.save_element_facturable');
    Route::match(['GET', 'POST'], 'save_equipe.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_equipe');
    Route::match(['GET', 'POST'], 'save_folder.php', [LegacyBridgeController::class, 'show'])->middleware('permission:47')->name('legacy_bridge.save_folder');
    Route::match(['GET', 'POST'], 'save_garde.php', [LegacyBridgeController::class, 'show'])->middleware('permission:6')->name('legacy_bridge.save_garde');
    Route::match(['GET', 'POST'], 'save_grades.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_grades');
    Route::match(['GET', 'POST'], 'save_habilitations.php', [LegacyBridgeController::class, 'show'])->middleware('permission:9')->name('legacy_bridge.save_habilitations');
    Route::match(['GET', 'POST'], 'save_hierarchie_competence.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_hierarchie_competence');
    Route::match(['GET', 'POST'], 'save_horaires.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_horaires');
    Route::match(['GET', 'POST'], 'save_info_adherent.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.save_info_adherent');
    Route::match(['GET', 'POST'], 'save_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_materiel');
    Route::match(['GET', 'POST'], 'save_password.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_password');
    Route::match(['GET', 'POST'], 'save_personnel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_personnel');
    Route::match(['GET', 'POST'], 'save_personnel_formation.php', [LegacyBridgeController::class, 'show'])->middleware('permission:4')->name('legacy_bridge.save_personnel_formation');
    Route::match(['GET', 'POST'], 'save_personnel_tenues.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_personnel_tenues');
    Route::match(['GET', 'POST'], 'save_piquet.php', [LegacyBridgeController::class, 'show'])->middleware('permission:6')->name('legacy_bridge.save_piquet');
    Route::match(['GET', 'POST'], 'save_poste.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_poste');
    Route::match(['GET', 'POST'], 'save_preferences.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_preferences');
    Route::match(['GET', 'POST'], 'save_prelevements.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.save_prelevements');
    Route::match(['GET', 'POST'], 'save_qualif.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_qualif');
    Route::match(['GET', 'POST'], 'save_qualif2.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_qualif2');
    Route::match(['GET', 'POST'], 'save_section.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_section');
    Route::match(['GET', 'POST'], 'save_type_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_type_consommable');
    Route::match(['GET', 'POST'], 'save_type_evenement.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_type_evenement');
    Route::match(['GET', 'POST'], 'save_type_garde.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_type_garde');
    Route::match(['GET', 'POST'], 'save_type_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_type_materiel');
    Route::match(['GET', 'POST'], 'save_type_vehicule.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.save_type_vehicule');
    Route::match(['GET', 'POST'], 'save_vehicule.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.save_vehicule');
    Route::match(['GET', 'POST'], 'scan_victime.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.scan_victime');
    Route::match(['GET', 'POST'], 'search_personnel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.search_personnel');
    Route::match(['GET', 'POST'], 'search_personnel_result.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.search_personnel_result');
    Route::match(['GET', 'POST'], 'section.php', fn () => redirect()->route('organisation.index'))->name('legacy_bridge.section');
    Route::match(['GET', 'POST'], 'section_stop.php', [LegacyBridgeController::class, 'show'])->middleware('permission:22')->name('legacy_bridge.section_stop');
    Route::match(['GET', 'POST'], 'send_id.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.send_id');
    Route::match(['GET', 'POST'], 'showfile.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.showfile');
    Route::match(['GET', 'POST'], 'sitac.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.sitac');
    Route::match(['GET', 'POST'], 'sitac_options.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.sitac_options');
    Route::match(['GET', 'POST'], 'sitac_save.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.sitac_save');
    Route::match(['GET', 'POST'], 'specific_info.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.specific_info');
    Route::match(['GET', 'POST'], 'tableau_garde.php', fn () => redirect()->route('garde.index'))->name('legacy_bridge.tableau_garde');
    Route::match(['GET', 'POST'], 'tableau_garde_create.php', [LegacyBridgeController::class, 'show'])->middleware('permission:5')->name('legacy_bridge.tableau_garde_create');
    Route::match(['GET', 'POST'], 'tableau_garde_status.php', [LegacyBridgeController::class, 'show'])->middleware('permission:5')->name('legacy_bridge.tableau_garde_status');
    Route::match(['GET', 'POST'], 'tableau_garde_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:61')->name('legacy_bridge.tableau_garde_xls');
    Route::match(['GET', 'POST'], 'trombinoscope.php', fn () => redirect()->route('personnel.trombinoscope'))->name('legacy_bridge.trombinoscope');
    Route::match(['GET', 'POST'], 'type_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.type_consommable');
    Route::match(['GET', 'POST'], 'type_evenement.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.type_evenement');
    Route::match(['GET', 'POST'], 'type_garde.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.type_garde');
    Route::match(['GET', 'POST'], 'type_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.type_materiel');
    Route::match(['GET', 'POST'], 'type_vehicule.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.type_vehicule');
    Route::match(['GET', 'POST'], 'upd_company.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.upd_company');
    Route::match(['GET', 'POST'], 'upd_company_role.php', [LegacyBridgeController::class, 'show'])->middleware('permission:37')->name('legacy_bridge.upd_company_role');
    Route::match(['GET', 'POST'], 'upd_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.upd_consommable');
    Route::match(['GET', 'POST'], 'upd_document.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.upd_document');
    Route::match(['GET', 'POST'], 'upd_element_facturable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:29')->name('legacy_bridge.upd_element_facturable');
    Route::match(['GET', 'POST'], 'upd_equipe.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.upd_equipe');
    Route::match(['GET', 'POST'], 'upd_folder.php', [LegacyBridgeController::class, 'show'])->middleware('permission:47')->name('legacy_bridge.upd_folder');
    Route::match(['GET', 'POST'], 'upd_grades.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upd_grades');
    Route::match(['GET', 'POST'], 'upd_habilitations.php', [LegacyBridgeController::class, 'show'])->middleware('permission:9')->name('legacy_bridge.upd_habilitations');
    Route::match(['GET', 'POST'], 'upd_hierarchie_competence.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upd_hierarchie_competence');
    Route::match(['GET', 'POST'], 'upd_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.upd_materiel');
    Route::match(['GET', 'POST'], 'upd_materiel_selector.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.upd_materiel_selector');
    Route::match(['GET', 'POST'], 'upd_personnel.php', function (\Illuminate\Http\Request $r) {
        $pid = (int) ($r->query('pompier') ?? $r->query('id') ?? 0);
        return $pid > 0
            ? redirect()->route('personnel.show', $pid)
            : redirect()->route('personnel.index');
    })->name('legacy_bridge.upd_personnel');
    Route::match(['GET', 'POST'], 'upd_personnel_salarie.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.upd_personnel_salarie');
    Route::match(['GET', 'POST'], 'upd_poste.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upd_poste');
    Route::match(['GET', 'POST'], 'upd_responsable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.upd_responsable');
    Route::match(['GET', 'POST'], 'upd_section.php', [LegacyBridgeController::class, 'show'])->middleware('permission:44')->name('legacy_bridge.upd_section');
    Route::match(['GET', 'POST'], 'upd_type_consommable.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upd_type_consommable');
    Route::match(['GET', 'POST'], 'upd_type_evenement.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upd_type_evenement');
    Route::match(['GET', 'POST'], 'upd_type_garde.php', [LegacyBridgeController::class, 'show'])->middleware('permission:5')->name('legacy_bridge.upd_type_garde');
    Route::match(['GET', 'POST'], 'upd_type_materiel.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upd_type_materiel');
    Route::match(['GET', 'POST'], 'upd_type_vehicule.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upd_type_vehicule');
    Route::match(['GET', 'POST'], 'upd_vehicule.php', function (\Illuminate\Http\Request $r) {
        $vid = (int) ($r->query('vehicule') ?? 0);
        return $vid > 0
            ? redirect()->route('vehicule.show', $vid)
            : redirect()->route('vehicule.index');
    })->name('legacy_bridge.upd_vehicule');
    Route::match(['GET', 'POST'], 'update_app.php', [LegacyBridgeController::class, 'show'])->middleware('permission:14')->name('legacy_bridge.update_app');
    Route::match(['GET', 'POST'], 'update_page.php', [LegacyBridgeController::class, 'show'])->middleware('permission:6')->name('legacy_bridge.update_page');
    Route::match(['GET', 'POST'], 'upgrade.php', [LegacyBridgeController::class, 'show'])->name('legacy_bridge.upgrade');
    Route::match(['GET', 'POST'], 'upload.php', [LegacyBridgeController::class, 'show'])->middleware('permission:18')->name('legacy_bridge.upload');
    Route::match(['GET', 'POST'], 'user_info.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.user_info');
    Route::match(['GET', 'POST'], 'vcard.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.vcard');
    Route::match(['GET', 'POST'], 'vehicule.php', fn () => redirect()->route('vehicule.index'))->name('legacy_bridge.vehicule');
    Route::match(['GET', 'POST'], 'vehicule_load.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.vehicule_load');
    Route::match(['GET', 'POST'], 'vehicule_xls.php', [LegacyBridgeController::class, 'show'])->middleware('permission:42')->name('legacy_bridge.vehicule_xls');
    Route::match(['GET', 'POST'], 'victimes.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.victimes');
    Route::match(['GET', 'POST'], 'virements.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.virements');
    Route::match(['GET', 'POST'], 'virements_extract.php', [LegacyBridgeController::class, 'show'])->middleware('permission:53')->name('legacy_bridge.virements_extract');
    Route::match(['GET', 'POST'], 'wizard.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.wizard');
    Route::match(['GET', 'POST'], 'zipcode.php', [LegacyBridgeController::class, 'show'])->middleware('permission:0')->name('legacy_bridge.zipcode');
});
