<?php

return [
    'legacy_root' => 'archive/legacy_app',
    'pages' => [
        'about.php' => [
            'route' => 'about',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'addons.php' => [
            'route' => 'addons',
            'permission' => 78,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'addons_save.php' => [
            'route' => 'addons_save',
            'permission' => 78,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'alerte_create.php' => [
            'route' => 'alerte_create',
            'permission' => 43,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'alerte_send.php' => [
            'route' => 'alerte_send',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'astreinte_edit.php' => [
            'route' => 'astreinte_edit',
            'permission' => 26,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'astreinte_save.php' => [
            'route' => 'astreinte_save',
            'permission' => 26,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'astreintes.php' => [
            'route' => 'astreintes',
            'permission' => 52,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'astreintes_updates.php' => [
            'route' => 'astreintes_updates',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'audit.php' => [
            'route' => 'audit',
            'permission' => 20,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'auto_garde.php' => [
            'route' => 'auto_garde',
            'permission' => 6,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'automaticPiquet.php' => [
            'route' => 'automaticPiquet',
            'permission' => 6,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'backup.php' => [
            'route' => 'backup',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'bilan_participation.php' => [
            'route' => 'bilan_participation',
            'permission' => 27,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'bilans.php' => [
            'route' => 'bilans',
            'permission' => 27,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'browscap.php' => [
            'route' => 'browscap',
            'permission' => null,
            'type' => 'script',
            'bridgeable' => false,
        ],
        'buildsql.php' => [
            'route' => 'buildsql',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'buildzipcode.php' => [
            'route' => 'buildzipcode',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'calendar.php' => [
            'route' => 'calendar',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'cav_edit.php' => [
            'route' => 'cav_edit',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'change_password.php' => [
            'route' => 'change_password',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'charte.php' => [
            'route' => 'charte',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'chat.php' => [
            'route' => 'chat',
            'permission' => null,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'chat_message.php' => [
            'route' => 'chat_message',
            'permission' => null,
            'type' => 'script',
            'bridgeable' => true,
        ],
        'choice_section_order.php' => [
            'route' => 'choice_section_order',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'company.php' => [
            'route' => 'company',
            'permission' => 29,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'company_xls.php' => [
            'route' => 'company_xls',
            'permission' => 29,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'config_doc.php' => [
            'route' => 'config_doc',
            'permission' => null,
            'type' => 'script',
            'bridgeable' => false,
        ],
        'config_prelevements.php' => [
            'route' => 'config_prelevements',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'configuration.php' => [
            'route' => 'configuration',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        '_configuration_db.php' => [
            'route' => '_configuration_db',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => false,
        ],
        'configuration_icone_grade.php' => [
            'route' => 'configuration_icone_grade',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'configuration_theme.php' => [
            'route' => 'configuration_theme',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'connected_users.php' => [
            'route' => 'connected_users',
            'permission' => 20,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'consommable.php' => [
            'route' => 'consommable',
            'permission' => 42,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'consommable_load.php' => [
            'route' => 'consommable_load',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'consommable_xls.php' => [
            'route' => 'consommable_xls',
            'permission' => 42,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'cotisation_edit.php' => [
            'route' => 'cotisation_edit',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'cotisations.php' => [
            'route' => 'cotisations',
            'permission' => 53,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'cotisations_extract.php' => [
            'route' => 'cotisations_extract',
            'permission' => 53,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'cotisations_xls.php' => [
            'route' => 'cotisations_xls',
            'permission' => 53,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'database_maintenance.php' => [
            'route' => 'database_maintenance',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'debug_data.php' => [
            'route' => 'debug_data',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'decrypt.php' => [
            'route' => 'decrypt',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'del_categorie_grade.php' => [
            'route' => 'del_categorie_grade',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_company.php' => [
            'route' => 'del_company',
            'permission' => 19,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_consommable.php' => [
            'route' => 'del_consommable',
            'permission' => 71,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_edit_categorie.php' => [
            'route' => 'del_edit_categorie',
            'permission' => 19,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_edit_categorie_consommable.php' => [
            'route' => 'del_edit_categorie_consommable',
            'permission' => 19,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_element_facturable.php' => [
            'route' => 'del_element_facturable',
            'permission' => 29,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_equipe.php' => [
            'route' => 'del_equipe',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_grade.php' => [
            'route' => 'del_grade',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_groupe.php' => [
            'route' => 'del_groupe',
            'permission' => 9,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_materiel.php' => [
            'route' => 'del_materiel',
            'permission' => 70,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_personnel.php' => [
            'route' => 'del_personnel',
            'permission' => 3,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_personnel_formation.php' => [
            'route' => 'del_personnel_formation',
            'permission' => 4,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_poste.php' => [
            'route' => 'del_poste',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_section.php' => [
            'route' => 'del_section',
            'permission' => 19,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_type_consommable.php' => [
            'route' => 'del_type_consommable',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_type_evenement.php' => [
            'route' => 'del_type_evenement',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_type_garde.php' => [
            'route' => 'del_type_garde',
            'permission' => 5,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_type_materiel.php' => [
            'route' => 'del_type_materiel',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_type_vehicule.php' => [
            'route' => 'del_type_vehicule',
            'permission' => 18,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'del_vehicule.php' => [
            'route' => 'del_vehicule',
            'permission' => 19,
            'type' => 'delete',
            'bridgeable' => true,
        ],
        'delete_event_file.php' => [
            'route' => 'delete_event_file',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'delete_file.php' => [
            'route' => 'delete_file',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'delete_message.php' => [
            'route' => 'delete_message',
            'permission' => null,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'delete_statistique.php' => [
            'route' => 'delete_statistique',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'deletePompier.php' => [
            'route' => 'deletePompier',
            'permission' => 6,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'demande_renfort.php' => [
            'route' => 'demande_renfort',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'departement.php' => [
            'route' => 'departement',
            'permission' => 52,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'destinataires.php' => [
            'route' => 'destinataires',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'diplome_edit.php' => [
            'route' => 'diplome_edit',
            'permission' => 54,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'dispo.php' => [
            'route' => 'dispo',
            'permission' => 38,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'document_modal.php' => [
            'route' => 'document_modal',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'documents.php' => [
            'route' => 'documents',
            'permission' => 44,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'download_addon.php' => [
            'route' => 'download_addon',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'download_module.php' => [
            'route' => 'download_module',
            'permission' => 78,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'download_package.php' => [
            'route' => 'download_package',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'dps.php' => [
            'route' => 'dps',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'dps_calc.php' => [
            'route' => 'dps_calc',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'dps_save.php' => [
            'route' => 'dps_save',
            'permission' => 15,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'edit_categorie.php' => [
            'route' => 'edit_categorie',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'edit_categorie_consommable.php' => [
            'route' => 'edit_categorie_consommable',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'edit_categorie_grades.php' => [
            'route' => 'edit_categorie_grades',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'edit_grades.php' => [
            'route' => 'edit_grades',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'element_facturable.php' => [
            'route' => 'element_facturable',
            'permission' => 29,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'equipe.php' => [
            'route' => 'equipe',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'error.php' => [
            'route' => 'error',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_add_renfort.php' => [
            'route' => 'evenement_add_renfort',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_choice.php' => [
            'route' => 'evenement_choice',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_competences.php' => [
            'route' => 'evenement_competences',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_consommable.php' => [
            'route' => 'evenement_consommable',
            'permission' => 42,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_consommable_add.php' => [
            'route' => 'evenement_consommable_add',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_detail.php' => [
            'route' => 'evenement_detail',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_diplome.php' => [
            'route' => 'evenement_diplome',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_display.php' => [
            'route' => 'evenement_display',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_duplicate.php' => [
            'route' => 'evenement_duplicate',
            'permission' => 15,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_edit.php' => [
            'route' => 'evenement_edit',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_equipes.php' => [
            'route' => 'evenement_equipes',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_facturation.php' => [
            'route' => 'evenement_facturation',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_facturation_detail.php' => [
            'route' => 'evenement_facturation_detail',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_facturation_num.php' => [
            'route' => 'evenement_facturation_num',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_garde.php' => [
            'route' => 'evenement_garde',
            'permission' => 6,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_horaires.php' => [
            'route' => 'evenement_horaires',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_ical.php' => [
            'route' => 'evenement_ical',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_info_participant.php' => [
            'route' => 'evenement_info_participant',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_inscription.php' => [
            'route' => 'evenement_inscription',
            'permission' => 39,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_list_xls.php' => [
            'route' => 'evenement_list_xls',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'evenement_materiel_add.php' => [
            'route' => 'evenement_materiel_add',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_modal.php' => [
            'route' => 'evenement_modal',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_multi_renforts.php' => [
            'route' => 'evenement_multi_renforts',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_notify.php' => [
            'route' => 'evenement_notify',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_option_choix.php' => [
            'route' => 'evenement_option_choix',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_options.php' => [
            'route' => 'evenement_options',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_rapport.php' => [
            'route' => 'evenement_rapport',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_save.php' => [
            'route' => 'evenement_save',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'evenement_tarif.php' => [
            'route' => 'evenement_tarif',
            'permission' => 15,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_tarif_formation.php' => [
            'route' => 'evenement_tarif_formation',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_trombinoscope.php' => [
            'route' => 'evenement_trombinoscope',
            'permission' => 44,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_vehicule_add.php' => [
            'route' => 'evenement_vehicule_add',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'evenement_vehicule_xls.php' => [
            'route' => 'evenement_vehicule_xls',
            'permission' => 42,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'evenement_xls.php' => [
            'route' => 'evenement_xls',
            'permission' => 41,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'evenements.php' => [
            'route' => 'evenements',
            'permission' => null,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'export-html.php' => [
            'route' => 'export_html',
            'permission' => null,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'export-sql-liste.php' => [
            'route' => 'export_sql_liste',
            'permission' => 27,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'export-sql.php' => [
            'route' => 'export_sql',
            'permission' => 27,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'export-tcd.php' => [
            'route' => 'export_tcd',
            'permission' => 27,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'export-txt.php' => [
            'route' => 'export_txt',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'export-xls.php' => [
            'route' => 'export_xls',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'export.php' => [
            'route' => 'export',
            'permission' => 27,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'export_badges.php' => [
            'route' => 'export_badges',
            'permission' => 14,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'feuille_garde.php' => [
            'route' => 'feuille_garde',
            'permission' => 61,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'formations_xls.php' => [
            'route' => 'formations_xls',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'geolocalize_all_persons.php' => [
            'route' => 'geolocalize_all_persons',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'gmaps_evenement.php' => [
            'route' => 'gmaps_evenement',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'gmaps_personnel.php' => [
            'route' => 'gmaps_personnel',
            'permission' => 76,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'gps.php' => [
            'route' => 'gps',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'gps_save.php' => [
            'route' => 'gps_save',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'gps_save2.php' => [
            'route' => 'gps_save2',
            'permission' => 76,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'grades_load.php' => [
            'route' => 'grades_load',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'habilitations.php' => [
            'route' => 'habilitations',
            'permission' => 52,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'habilitations_xls.php' => [
            'route' => 'habilitations_xls',
            'permission' => 40,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'hierarchie_competence.php' => [
            'route' => 'hierarchie_competence',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'histo_sms.php' => [
            'route' => 'histo_sms',
            'permission' => 23,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'history.php' => [
            'route' => 'history',
            'permission' => 49,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'homonymes_manage.php' => [
            'route' => 'homonymes_manage',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'homonymes_modal.php' => [
            'route' => 'homonymes_modal',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'horaires.php' => [
            'route' => 'horaires',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'horaires_modal.php' => [
            'route' => 'horaires_modal',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'import_api.php' => [
            'route' => 'import_api',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'index.php' => [
            'route' => 'index',
            'permission' => null,
            'type' => 'dashboard',
            'bridgeable' => true,
        ],
        'index_d.php' => [
            'route' => 'index_d',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'indispo.php' => [
            'route' => 'indispo',
            'permission' => 11,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'indispo_choice.php' => [
            'route' => 'indispo_choice',
            'permission' => 11,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'indispo_display.php' => [
            'route' => 'indispo_display',
            'permission' => 11,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'indispo_list_xls.php' => [
            'route' => 'indispo_list_xls',
            'permission' => 56,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'indispo_save.php' => [
            'route' => 'indispo_save',
            'permission' => 11,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'indispo_status.php' => [
            'route' => 'indispo_status',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'ins_company.php' => [
            'route' => 'ins_company',
            'permission' => 29,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'ins_groupe.php' => [
            'route' => 'ins_groupe',
            'permission' => 9,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'ins_materiel.php' => [
            'route' => 'ins_materiel',
            'permission' => 70,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'ins_personnel.php' => [
            'route' => 'ins_personnel',
            'permission' => 0,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'ins_poste.php' => [
            'route' => 'ins_poste',
            'permission' => 18,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'ins_section.php' => [
            'route' => 'ins_section',
            'permission' => 55,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'ins_type_materiel.php' => [
            'route' => 'ins_type_materiel',
            'permission' => 18,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'ins_vehicule.php' => [
            'route' => 'ins_vehicule',
            'permission' => 17,
            'type' => 'create',
            'bridgeable' => true,
        ],
        'install_addon.php' => [
            'route' => 'install_addon',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'intervention_edit.php' => [
            'route' => 'intervention_edit',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'jvectormap.php' => [
            'route' => 'jvectormap',
            'permission' => 27,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'liste_victimes.php' => [
            'route' => 'liste_victimes',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'listecontacts.php' => [
            'route' => 'listecontacts',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'listemails.php' => [
            'route' => 'listemails',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'livesearch.php' => [
            'route' => 'livesearch',
            'permission' => 40,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'localize.php' => [
            'route' => 'localize',
            'permission' => 43,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'localize_me.php' => [
            'route' => 'localize_me',
            'permission' => null,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'localize_send.php' => [
            'route' => 'localize_send',
            'permission' => 23,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'lost_password.php' => [
            'route' => 'lost_password',
            'permission' => null,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'lost_session.php' => [
            'route' => 'lost_session',
            'permission' => null,
            'type' => 'script',
            'bridgeable' => true,
        ],
        'mail_create.php' => [
            'route' => 'mail_create',
            'permission' => 43,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'mail_create_input.php' => [
            'route' => 'mail_create_input',
            'permission' => 43,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'mail_send.php' => [
            'route' => 'mail_send',
            'permission' => 43,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'mailer.php' => [
            'route' => 'mailer',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'mailto.php' => [
            'route' => 'mailto',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'map.php' => [
            'route' => 'map',
            'permission' => 76,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'materiel.php' => [
            'route' => 'materiel',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'materiel_embarquer.php' => [
            'route' => 'materiel_embarquer',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'materiel_load.php' => [
            'route' => 'materiel_load',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'materiel_xls.php' => [
            'route' => 'materiel_xls',
            'permission' => 42,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'membres.php' => [
            'route' => 'membres',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'menu_status_set.php' => [
            'route' => 'menu_status_set',
            'permission' => null,
            'type' => 'script',
            'bridgeable' => true,
        ],
        'message.php' => [
            'route' => 'message',
            'permission' => 44,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'myagenda.php' => [
            'route' => 'myagenda',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'noscript.php' => [
            'route' => 'noscript',
            'permission' => null,
            'type' => 'script',
            'bridgeable' => true,
        ],
        'note_frais_edit.php' => [
            'route' => 'note_frais_edit',
            'permission' => 77,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'note_frais_save.php' => [
            'route' => 'note_frais_save',
            'permission' => 77,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'observations_modal.php' => [
            'route' => 'observations_modal',
            'permission' => 53,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'organigramme.php' => [
            'route' => 'organigramme',
            'permission' => 44,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'parametrage.php' => [
            'route' => 'parametrage',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'paramfn.php' => [
            'route' => 'paramfn',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'paramfn_edit.php' => [
            'route' => 'paramfn_edit',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'paramfn_save.php' => [
            'route' => 'paramfn_save',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'paramfnv.php' => [
            'route' => 'paramfnv',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'paramfnv_edit.php' => [
            'route' => 'paramfnv_edit',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'paramfnv_save.php' => [
            'route' => 'paramfnv_save',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'participations_modal.php' => [
            'route' => 'participations_modal',
            'permission' => 56,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'pdf.php' => [
            'route' => 'pdf',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'pdf_asa.php' => [
            'route' => 'pdf_asa',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_attestation_fiscale.php' => [
            'route' => 'pdf_attestation_fiscale',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_attestation_formation.php' => [
            'route' => 'pdf_attestation_formation',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_bilans.php' => [
            'route' => 'pdf_bilans',
            'permission' => 27,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_bulletin.php' => [
            'route' => 'pdf_bulletin',
            'permission' => 44,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_carte_adherent.php' => [
            'route' => 'pdf_carte_adherent',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_courrier_nouvel_adherent.php' => [
            'route' => 'pdf_courrier_nouvel_adherent',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_diplome.php' => [
            'route' => 'pdf_diplome',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_document.php' => [
            'route' => 'pdf_document',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'pdf_livret.php' => [
            'route' => 'pdf_livret',
            'permission' => 0,
            'type' => 'pdf',
            'bridgeable' => true,
        ],
        'personnel.php' => [
            'route' => 'personnel',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'personnel_contact.php' => [
            'route' => 'personnel_contact',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'personnel_evenement_xls.php' => [
            'route' => 'personnel_evenement_xls',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'personnel_formation.php' => [
            'route' => 'personnel_formation',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'personnel_load.php' => [
            'route' => 'personnel_load',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'personnel_maitre.php' => [
            'route' => 'personnel_maitre',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'personnel_preferences.php' => [
            'route' => 'personnel_preferences',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'personnel_reunion_xls.php' => [
            'route' => 'personnel_reunion_xls',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'personnel_tenues.php' => [
            'route' => 'personnel_tenues',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'personnel_xls.php' => [
            'route' => 'personnel_xls',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'planning.php' => [
            'route' => 'planning',
            'permission' => 56,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'planning_xls.php' => [
            'route' => 'planning_xls',
            'permission' => 56,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'poste.php' => [
            'route' => 'poste',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'prelevements.php' => [
            'route' => 'prelevements',
            'permission' => 53,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'push_monitor.php' => [
            'route' => 'push_monitor',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'qrcode.php' => [
            'route' => 'qrcode',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'qrcode_pic.php' => [
            'route' => 'qrcode_pic',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'qualifications.php' => [
            'route' => 'qualifications',
            'permission' => 56,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'qualifications_xls.php' => [
            'route' => 'qualifications_xls',
            'permission' => 0,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'radier_section.php' => [
            'route' => 'radier_section',
            'permission' => 22,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'rebuild_section_flat.php' => [
            'route' => 'rebuild_section_flat',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'reminder.php' => [
            'route' => 'reminder',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'remplacement_edit.php' => [
            'route' => 'remplacement_edit',
            'permission' => null,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'remplacements.php' => [
            'route' => 'remplacements',
            'permission' => 41,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'repo_events.php' => [
            'route' => 'repo_events',
            'permission' => 27,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'report_cotisations.php' => [
            'route' => 'report_cotisations',
            'permission' => 53,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'repos_saisie.php' => [
            'route' => 'repos_saisie',
            'permission' => 10,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'repos_save.php' => [
            'route' => 'repos_save',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'restore.php' => [
            'route' => 'restore',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'rss.php' => [
            'route' => 'rss',
            'permission' => null,
            'type' => 'script',
            'bridgeable' => true,
        ],
        'save_accueil.php' => [
            'route' => 'save_accueil',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_company.php' => [
            'route' => 'save_company',
            'permission' => 29,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_configuration.php' => [
            'route' => 'save_configuration',
            'permission' => 14,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_consommable.php' => [
            'route' => 'save_consommable',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_cotisations.php' => [
            'route' => 'save_cotisations',
            'permission' => 53,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_detail_facture.php' => [
            'route' => 'save_detail_facture',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_dispo.php' => [
            'route' => 'save_dispo',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_documents.php' => [
            'route' => 'save_documents',
            'permission' => 47,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_edit_categorie.php' => [
            'route' => 'save_edit_categorie',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_edit_categorie_consommable.php' => [
            'route' => 'save_edit_categorie_consommable',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_edit_categorie_grades.php' => [
            'route' => 'save_edit_categorie_grades',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_element_facturable.php' => [
            'route' => 'save_element_facturable',
            'permission' => 17,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_equipe.php' => [
            'route' => 'save_equipe',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_folder.php' => [
            'route' => 'save_folder',
            'permission' => 47,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_garde.php' => [
            'route' => 'save_garde',
            'permission' => 6,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_grades.php' => [
            'route' => 'save_grades',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_habilitations.php' => [
            'route' => 'save_habilitations',
            'permission' => 9,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_hierarchie_competence.php' => [
            'route' => 'save_hierarchie_competence',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_horaires.php' => [
            'route' => 'save_horaires',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_info_adherent.php' => [
            'route' => 'save_info_adherent',
            'permission' => 53,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_materiel.php' => [
            'route' => 'save_materiel',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_password.php' => [
            'route' => 'save_password',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_personnel.php' => [
            'route' => 'save_personnel',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_personnel_formation.php' => [
            'route' => 'save_personnel_formation',
            'permission' => 4,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_personnel_tenues.php' => [
            'route' => 'save_personnel_tenues',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_piquet.php' => [
            'route' => 'save_piquet',
            'permission' => 6,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_poste.php' => [
            'route' => 'save_poste',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_preferences.php' => [
            'route' => 'save_preferences',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_prelevements.php' => [
            'route' => 'save_prelevements',
            'permission' => 53,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_qualif.php' => [
            'route' => 'save_qualif',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_qualif2.php' => [
            'route' => 'save_qualif2',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_section.php' => [
            'route' => 'save_section',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_type_consommable.php' => [
            'route' => 'save_type_consommable',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_type_evenement.php' => [
            'route' => 'save_type_evenement',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_type_garde.php' => [
            'route' => 'save_type_garde',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_type_materiel.php' => [
            'route' => 'save_type_materiel',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_type_vehicule.php' => [
            'route' => 'save_type_vehicule',
            'permission' => 18,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'save_vehicule.php' => [
            'route' => 'save_vehicule',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'scan_victime.php' => [
            'route' => 'scan_victime',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'search_personnel.php' => [
            'route' => 'search_personnel',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'search_personnel_result.php' => [
            'route' => 'search_personnel_result',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'section.php' => [
            'route' => 'section',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'section_stop.php' => [
            'route' => 'section_stop',
            'permission' => 22,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'send_id.php' => [
            'route' => 'send_id',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'showfile.php' => [
            'route' => 'showfile',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'sitac.php' => [
            'route' => 'sitac',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'sitac_options.php' => [
            'route' => 'sitac_options',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'sitac_save.php' => [
            'route' => 'sitac_save',
            'permission' => 0,
            'type' => 'save',
            'bridgeable' => true,
        ],
        'specific_info.php' => [
            'route' => 'specific_info',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'tableau_garde.php' => [
            'route' => 'tableau_garde',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'tableau_garde_create.php' => [
            'route' => 'tableau_garde_create',
            'permission' => 5,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'tableau_garde_status.php' => [
            'route' => 'tableau_garde_status',
            'permission' => 5,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'tableau_garde_xls.php' => [
            'route' => 'tableau_garde_xls',
            'permission' => 61,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'trombinoscope.php' => [
            'route' => 'trombinoscope',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'type_consommable.php' => [
            'route' => 'type_consommable',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'type_evenement.php' => [
            'route' => 'type_evenement',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'type_garde.php' => [
            'route' => 'type_garde',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'type_materiel.php' => [
            'route' => 'type_materiel',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'type_vehicule.php' => [
            'route' => 'type_vehicule',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'upd_company.php' => [
            'route' => 'upd_company',
            'permission' => 0,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_company_role.php' => [
            'route' => 'upd_company_role',
            'permission' => 37,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_consommable.php' => [
            'route' => 'upd_consommable',
            'permission' => 42,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_document.php' => [
            'route' => 'upd_document',
            'permission' => 0,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_element_facturable.php' => [
            'route' => 'upd_element_facturable',
            'permission' => 29,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_equipe.php' => [
            'route' => 'upd_equipe',
            'permission' => 0,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_folder.php' => [
            'route' => 'upd_folder',
            'permission' => 47,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_grades.php' => [
            'route' => 'upd_grades',
            'permission' => 18,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_habilitations.php' => [
            'route' => 'upd_habilitations',
            'permission' => 9,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_hierarchie_competence.php' => [
            'route' => 'upd_hierarchie_competence',
            'permission' => 18,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_materiel.php' => [
            'route' => 'upd_materiel',
            'permission' => 42,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_materiel_selector.php' => [
            'route' => 'upd_materiel_selector',
            'permission' => 42,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_personnel.php' => [
            'route' => 'upd_personnel',
            'permission' => 0,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_personnel_salarie.php' => [
            'route' => 'upd_personnel_salarie',
            'permission' => 0,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_poste.php' => [
            'route' => 'upd_poste',
            'permission' => 18,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_responsable.php' => [
            'route' => 'upd_responsable',
            'permission' => 0,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_section.php' => [
            'route' => 'upd_section',
            'permission' => 44,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_type_consommable.php' => [
            'route' => 'upd_type_consommable',
            'permission' => 18,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_type_evenement.php' => [
            'route' => 'upd_type_evenement',
            'permission' => 18,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_type_garde.php' => [
            'route' => 'upd_type_garde',
            'permission' => 5,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_type_materiel.php' => [
            'route' => 'upd_type_materiel',
            'permission' => 18,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_type_vehicule.php' => [
            'route' => 'upd_type_vehicule',
            'permission' => 18,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'upd_vehicule.php' => [
            'route' => 'upd_vehicule',
            'permission' => 42,
            'type' => 'edit',
            'bridgeable' => true,
        ],
        'update_app.php' => [
            'route' => 'update_app',
            'permission' => 14,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'update_page.php' => [
            'route' => 'update_page',
            'permission' => 6,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'upgrade.php' => [
            'route' => 'upgrade',
            'permission' => null,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'upload.php' => [
            'route' => 'upload',
            'permission' => 18,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'user_info.php' => [
            'route' => 'user_info',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'vcard.php' => [
            'route' => 'vcard',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'vehicule.php' => [
            'route' => 'vehicule',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'vehicule_load.php' => [
            'route' => 'vehicule_load',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'vehicule_xls.php' => [
            'route' => 'vehicule_xls',
            'permission' => 42,
            'type' => 'export',
            'bridgeable' => true,
        ],
        'victimes.php' => [
            'route' => 'victimes',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'virements.php' => [
            'route' => 'virements',
            'permission' => 53,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'virements_extract.php' => [
            'route' => 'virements_extract',
            'permission' => 53,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'wizard.php' => [
            'route' => 'wizard',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
        'zipcode.php' => [
            'route' => 'zipcode',
            'permission' => 0,
            'type' => 'page',
            'bridgeable' => true,
        ],
    ],
];
